"""Explicit on-disk dataset and schema versions."""

DATASET_VERSION = 1
RAW_TRADE_SCHEMA_VERSION = 1
RAW_DEPTH_SCHEMA_VERSION = 1
TRUSTED_BOOK_SCHEMA_VERSION = 1
LIFECYCLE_SCHEMA_VERSION = 2
CLOCK_SCHEMA_VERSION = 2
FEATURE_SCHEMA_VERSION = 2
BOOTSTRAP_SCHEMA_VERSION = 1
